---
title: "metaquantome-usage"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
```


# Data

## Full GO CPM

```{r}
full_go_cpm <- read.delim('data/full_go_cpm.tab', stringsAsFactors = FALSE)
full_go_cpm
```

# MetaQuantome

## Writing input files

```{r cars}
write_mqome_inputs <- function(name, df, header, col_gos, col_samp1, col_samp2, col_samp3) {
  int_df <- df[c(header, col_samp1, col_samp2, col_samp3)] 
  names(int_df)[1] <- 'id'
  write.table(int_df,
              file=paste0("data/inputs/", name, "_int.tab"),
              quote=FALSE, row.names=FALSE, sep="\t")
  func_df <- df[c(header, col_gos)]
  names(func_df) <- c('id', 'gos')
  write.table(func_df,
              file=paste0("data/inputs/", name, "_func.tab"),
              quote=FALSE, row.names=FALSE, sep="\t")
}
write_mqome_inputs('T4', full_go_cpm, 'id', 'id', 'T4A', 'T4B', 'T4C')
write_mqome_inputs('T7', full_go_cpm, 'id', 'id', 'T7A', 'T7B', 'T7C')
```

## Print metaQuantome commands

Copy and paste the output commands to create the expanded and filtered files:

```{r}
print_mqome_cmds <- function(name, func_colname){
  id <- 'id'
  cmd_expand <- paste0("metaquantome expand --mode f --data_dir data/go_db/",
                        " --int_file data/inputs/", name, "_int.tab",
                       " --pep_colname_int ", id,
                       " --func_file data/inputs/", name, "_func.tab",
                       " --pep_colname_func ", id,
                       " --func_colname ", func_colname," --ontology go",
                       " --samps data/inputs/samples_", name, ".tab",
                       " --outfile data/outputs/", name, "_func_expanded.tab")
  cmd_filt <- paste0("metaquantome filter",
                     " --expand_file data/outputs/", name, "_func_expanded.tab",
                     " --mode f --ontology go",
                     " --samps data/inputs/samples_", name, ".tab",
                     " --min_peptides 2 --min_pep_nsamp 0 --min_children_non_leaf 2 --min_child_nsamp 1",
                     " --qthreshold 0 --outfile data/outputs/", name, "_func_filtered.tab")
  return(paste(cmd_expand, 
               cmd_filt,
               sep='; '))
}
paste(print_mqome_cmds("T4", 'gos'),
      print_mqome_cmds("T7", 'gos'),
      sep='; ')
```

## Importing Expanded and Filtered Files

```{r}
import_mqome_output <- function(name, type){
  read.delim(paste0("data/outputs/", name, "_func_", type, ".tab"),
             stringsAsFactors = FALSE) %>%
    rename(gos = id)
}
t4_expanded <- import_mqome_output('T4', 'expanded')
t4_filtered <- import_mqome_output('T4', 'filtered')
t7_expanded <- import_mqome_output('T7', 'expanded')
t7_filtered <- import_mqome_output('T7', 'filtered')
```

```{r}
full_go_cpm
```

```{r}
t4_expanded
```

```{r}
t7_expanded
```


```{r}
t4_filtered
```

## Filtering to only nodes or only ancestors

```{r}
filter_to_nodes <- function(df){
  colnames <- names(df)
  df[is.na(df[colnames[grepl('n_samp_children', colnames)]]),] %>% filter(!is.na(gos))
}
filter_to_ancestors <-function(df){
  colnames <- names(df)
  df[!is.na(df[colnames[grepl('n_samp_children', colnames)]]),] %>% filter(!is.na(gos))
}
t4_filtered_nodes <- filter_to_nodes(t4_filtered)
t4_expanded_nodes <- filter_to_nodes(t4_expanded)
t4_filtered_ancestors <- filter_to_ancestors(t4_filtered)
t4_expanded_ancestors <- filter_to_ancestors(t4_expanded)
t7_filtered_nodes <- filter_to_nodes(t7_filtered)
t7_expanded_nodes <- filter_to_nodes(t7_expanded)
t7_filtered_ancestors <- filter_to_ancestors(t7_filtered)
t7_expanded_ancestors <- filter_to_ancestors(t7_expanded)
```

```{r}
t4_expanded
```

```{r}
t4_expanded_nodes
```

```{r}
t7_expanded
```

```{r}
t7_expanded_nodes
```

